### PR TITLE
Update decoder Alarm for "StartekProtocolDecoder.java"

### PR DESCRIPTION
**Pull request by Theerayuttu**
Update to add more decoder Alarm for Startek Protocol (StartekProtocolDecoder.java)

ALARM_LOW_POWER
ALARM_POWER_CUT
ALARM_POWER_RESTORED

Please review. thank you.

### CODE REVIEW

**Comment by tananaev** [comment]
Please provide the protocol documentation.

**Comment by Theerayuttu** [comment]
[istartek gps tracker communication protocol v1.4.pdf](https://github.com/traccar/traccar/files/13946099/istartek.gps.tracker.communication.protocol.v1.4.pdf)

Refer Alarm even code on page 50
Thank you.

**Comment by tananaev** [comment]
Merged, thanks.

**Comment by Theerayuttu** [comment]
> Merged, thanks.

Thank you.

**Pull request merged**
