### PR TITLE
Odometer in reports only

### PR DESCRIPTION
**Pull request by ckrey**
Implements Odometer in Summary, Trips, and Stops Reports traccar/traccar-web#652
relies on corresponding PR in traccar/traccar-web

### CODE REVIEW

**Comment by tananaev** [comment]
In stops report shouldn't we just call it odometer?

**Comment by ckrey** [comment]
we can do so but

a) Stop report shares startOdometer and endOdometer members from BaseReport
b) Technically a Stop is a set of positions with a start and end as summary or trip are although the odometer is not expected to change much between start and end

**Comment by tananaev** [comment]
I'm talking about display part. I'm fine with storing it as it is internally.

**Comment by ckrey** [comment]
ok done

**Comment by tananaev** [comment]
Can you please clean up branch history. The list of commits is huge and some of them are completely irrelevant to this pull request.

**Pull request closed without merging**
