### PR TITLE
Support for NDTPv6 protocol

### PR DESCRIPTION
**Pull request by anton2920**
This branch adds support for NDTPv6 protocol.

### CODE REVIEW

**Comment by tananaev** [comment]
Is this ready for review?

**Comment by anton2920** [comment]
Unfortunately, I don't have examples for this one :(

**Comment by tananaev** [comment]
How did you test it without any examples?

**Comment by tananaev** [comment]
Also did a refactoring - https://github.com/traccar/traccar/commit/8532bffcec8e239c6699845e09e63da927f51d9a. It would be nice if you can test it and provide some samples because we don't have any test cases.

**Pull request merged**
