### PR TITLE
fixed exception when String.format thought the binary data has formt placeholders

### PR DESCRIPTION
**Pull request by flocsy**

### CODE REVIEW

**Comment by tananaev** [comment]
Please include unit test.

**Comment by flocsy** [comment]
the existing unittest covers it, that's why the 1st commit failed

**Comment by tananaev** [comment]
Well, can we have test case for the different behavior?

**Comment by flocsy** [comment]
Added a test. It passes with:
return formatCommand(channel, command, "TK,%s", getBinaryData(command));
but fails with the old:
return formatCommand(channel, command, "TK," + getBinaryData(command));

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
