### PR TITLE
refactor to make possible to use other sms provider

### PR DESCRIPTION
**Pull request by ivanfmartinez**

### CODE REVIEW

**Comment by ivanfmartinez** [comment]
this will make easier to implement a class to close  #3111 #3613 and #3636

**Comment by tananaev** [comment]
I think it would be better to generalise not just SMS manager, but all notification options.

**Comment by ivanfmartinez** [comment]
I agree that the full notifications can be refactored, but in this case the SMS is an notification type and my refactor is just to select the provider for send the SMS.

This simple refactor can make possible to possible to attach new SMS providers.

To make all notifications attachable we must make structural changes to database and web UI also.

**Comment by tananaev** [comment]
I still think we should implement universal solution for all notifications, not just SMS.

**Comment by ivanfmartinez** [comment]
probably you should create a table for the notification methods, and this table can have the definition including the class to be used to process the notification.

the tables which currently have email, sms and web setting should be changed to use this notification 
methods reference and also the destination for the notification method.

At this moment I can see extra notification types :
 MQTT 
 URL call with GET or POST

But the SMS are also used for sending configuration to the devices, and in this case the SMS should still have the getSmsManager method in the Context class to send this commands to the devices.

This PR is simple and make possible to use other SMS providers by just defining one new class and keeping full compatibility with current versions. The refactor for notifications is a good thing to be done (I like this idea), but requires more planing because will have DB and UI changes .

**Comment by tananaev** [comment]
I don't think we need to store classes in the database. Configuration file should be enough.

**Comment by ivanfmartinez** [comment]
The current config only read by key, in this case we need an notification definition and then the class like this ?

    <entry key='notification.types'>sms,mqtt,get</entry>
    <entry key='notification.sms.class'>org.traccar.sms.SMSNotitificatior</entry>
    <entry key='notification.mqtt.class'>org.traccar.mqtt.MQTTNotitificatior</entry>
    <entry key='notification.get.class'>package.HttpGetNotitificatior</entry>

In this case we cannot ensure the integrity of the definitions in the database if someone remove the "mqtt"  notification type and there still an configured notification using this type.

The definitions like description will be at database or in the config xml ?

**Comment by tananaev** [comment]
Why do we need anything in the database? I would imagine that set of available notification providers would be fixed for a server, so we don't need to keep anything in the database. Definition can also be in the config.

**Comment by ivanfmartinez** [comment]
The user has to decide where the notifications will go. 

The notifications table has columns web, mail, sms that are direclty linked to the code in traccar. 

Creating generic notifications this has to be changed to relate the notifications record to the notifications implementations.

**Comment by tananaev** [comment]
Of course we would need user notifications config in the database, but configuration on notification providers themselves can be static in the config.

**Comment by ivanfmartinez** [comment]
traccar 4.3 has support for the configurable notitfication providers and SMS http providers

**Pull request closed without merging**
