### PR TITLE
Totem - add some basic commands

### PR DESCRIPTION
**Pull request by jinzo**
Added some basic commands that I needed for Totem - willing to extend it to full available list down the line. 
But wanted to open this PR and ask if there is a way to handle SMS and GPRS commands? And which Protocol implements that - as I checked some popular ones and did not find any. Would like to implement either sending via SMS or via GPRS, but need some help/example on how this is handled elsewhere. Thanks!

### CODE REVIEW

**Comment by tananaev** [comment]
Can you please attach protocol documentation, so we have a record of it here.

**Comment by jinzo** [comment]
I already sent you the documentation via mail on 16.10.2021 (to both Gmail
and Traccar email). It's the only docs on Totemtek I have.

**Comment by tananaev** [comment]
I understand that, but can you please attach it to the ticket, so everyone has a reference.

**Comment by jinzo** [comment]
I finally tracked down the original link where I got all the files (not only protocol, but other documents too):
- [Root Folder](https://www.dropbox.com/sh/d546ygmpc4jvfah/AAAlmHe7RjzjYyd3BpfM94IAa?dl=0&tdsourcetag=s_pcqq_aiomsg)
- [AT05](https://www.dropbox.com/sh/d546ygmpc4jvfah/AABJs0FbExLmqRVJ7N9c9rnda/01AT05%202G?dl=0&preview=04-GPS-Tracker-AT05-2G-protocol%26commands-V2.56.pdf&subfolder_nav_tracking=1)
- [AT07](https://www.dropbox.com/sh/d546ygmpc4jvfah/AAASXiFCrb3RiOX8hb-5N-5Ga/02AT07%202G?dl=0&preview=04-GPS-Tracker-AT07-2G-protocol%26commands-V2.49.pdf&subfolder_nav_tracking=1)
- [AT09](https://www.dropbox.com/sh/d546ygmpc4jvfah/AADL0PNtoJPwpZUUaAcDuSa0a/03AT09%202G?dl=0&preview=04-GPS-Tracker-AT09-2G-protocol%26commands-V2.41.pdf&subfolder_nav_tracking=1)

**Comment by tananaev** [comment]
Merged, thank you.

**Comment by jinzo** [comment]
Hi, thanks for the merge. 
This protocol/devices support two ways of sending the commands - via SMS or via GPRS. I would like to implement both options if possible. So when user checks the SMS checkbox it gets sent as SMS, but when it's unchecked it gets sent via GPRS. But I am not sure how to implement this. 

Is this even possible with Traccar currently? Do you know of any protocols that implement this so I can take a look?

Thanks for your time!

**Comment by tananaev** [comment]
Check other examples. It is possible. You need a separate encoder for SMS. Search for `setSupportedTextCommands` in the code to find examples.

**Pull request merged**
