### PR TITLE
Adding event handler for detecting engine start or stop using car's power voltage

### PR DESCRIPTION
**Pull request by lalamper**
This event handler is for detecting engine start or stop using car's power voltage.

ATTRIBUTE_ENGINE_START_STOP_POWER_THRESHOLD can be defined with a specific voltage level of car power.
According to my measures 14.00V can be working level.

If this voltage drops below the threshold and previously it was higher, it means engine has stopped (car's power generator does not operate)
If voltage gets higher than threshold and previously it was lower, it means engine has started (car's power generator operates)

May need to change code in other files as well.

### CODE REVIEW

**Comment by lalamper** [comment]
Hi Anton,
Can you please help me out with this type error?
Thanks!

double power = position.getAttributes().containsKey(Position.KEY_POWER);
[ERROR] /home/travis/build/tananaev/traccar/src/org/traccar/events/EngineStartStopEventHandler.java:[53,60] incompatible types
[ERROR] required: double
[ERROR] found:    boolean

oldPower = lastPosition.getAttributes().containsKey(Position.KEY_POWER);
[ERROR] /home/travis/build/tananaev/traccar/src/org/traccar/events/EngineStartStopEventHandler.java:[59,64] incompatible types
[ERROR] required: double
[ERROR] found:    boolean

**Comment by tananaev** [comment]
There is already an ignition event handler that does this. Why do we need another one?

**Comment by lalamper** [comment]
Current ignition handler only looks for KEY_IGNITION value, which needed to be set by the protocol decoder implementation. It works only if the currently used protocol and device support this information (most of the devices do not provide it)

My event handler works different, independently from this flag in the protocol. It follows different logic, based on voltage level, it can be used with all protocol which provides car's voltage.

On the other hand, ignition and starting/stopping the engine are not the same exactly. In modern cars ignition is a status without running engine, but with all electric part prepared operating.

I was thinking to modify the current event handler or create a new, I decided to set up a new.
What do you think?

**Comment by tananaev** [comment]
I think the right thing would probably be to set "ignition" flag based on the voltage level instead of implementing completely separate event.

**Comment by lalamper** [comment]
Did you mean to implement it into each protocol one by one, or into the current IgnitionEventHandler.java with a condition to check for this voltage level attribute?

**Comment by tananaev** [comment]
No, you can implement a pipeline handler for that as well, so it would work for any protocol.

**Comment by lalamper** [comment]
Sorry, I do not know how pipeline handler works and how to do that.
Is there any documentation for that?

**Comment by tananaev** [comment]
You've implemented one.

**Comment by lalamper** [comment]
"You've implemented one." - this does not help me, sorry. I am not a programmer. Maybe a little bit more explanation would be fine.

**Comment by tananaev** [comment]
So you don't even know what you implemented? I would recommend to read Netty 3 documentation for more explanation.

**Comment by lalamper** [comment]
I will try to implement this feature into existing IgnitionEventHandler.java. If voltage level attribute exists it will be used to detect ignition.
Are you OK with this?

**Comment by tananaev** [comment]
No, I think it should be another separate handler.

**Comment by lalamper** [comment]
Ok, I will try to finalize EngineStartStopEventHandler.java in the next few days.

**Comment by tananaev** [comment]
Well, I think you still misunderstand what I proposed.

**Comment by lalamper** [comment]
Maybe if you could put a little bit more effort into pointing me to the right direction, I would be more happy. Sorry, but your answer really does not help.

**Comment by tananaev** [comment]
I am proposing a handler that would add ignition flag to the position based on the power value, if it's not reported by the device.

**Comment by lalamper** [comment]
Which file needs to be modified?

**Comment by tananaev** [comment]
You need to create a new class.

**Comment by lalamper** [comment]
Hi Anton,

I think we should reconsider the whole approach. There are two ways to implement this.

1. Creating a separate event handler (EngineStartStopEventHandler.java) for detecting engine start/stop based on the voltage level if threshold set.
This would work independently from the existing ignition event handler. In this case a new event handler java needed.

I think this is the better solution, because ignition on/off and engine start/stop are completely different actions in real world.

2. Or we can use the existing ignition event handler to manage engine start/stop. For this, existing IgnitionEventHandler.java should be extended to check for the threshold attribute (if no KEY_IGNITION flag set by the protocol) and generate ignition event based on voltage level.
In this case there is no need a separate handler java file, because it has no sense.

**Comment by tananaev** [comment]
Both options are different from what I'm proposing. I don't like either of them because you are assuming that "ignition" flag is used only for ignition notification.

**Comment by lalamper** [comment]
Not really see what else ignition flag can indicate? Let's see a simple case.

You insert your car key and turn it into stage 1. Now you have ignition, but the engine does not run. If a device can report this, ignition on event generated. If you turn your key to stage 2, you still have ignition and a running engine. Now you turn backwards your key, back to stage 1: your engine is stopped, but you still have ignition. In next step your turn your key backwards again: ignition is off.

If this does not OK with you, then what is your proposal (logic)? I do not still see what you mention.

If I understand well, ignition flag is set (or not) by the protocol at first. Then come the event handlers into the picture, one by one. They are generating events based on some logic.

**Comment by tananaev** [comment]
I suggest to calculate ignition flag based on the power level if protocol doesn't include it. Similar to distance handler.

Ignition flag can potentially be used for trips report or something else in future.

**Comment by lalamper** [comment]
Ok, I will try to implement soon.

**Comment by ermalbaj** [comment]
Lalamper did you implemented this feature ?
Im interested too...

**Comment by lalamper** [comment]
Hi, unfortunatelly I have very few free time in the last month, but I did not give up.
It would be nice to finish it. I will try to fix it in the next weeks.
Any help appropriated. :)

**Comment by tsmgeek** [comment]
@tananaev device may report ignition flag as it could be in protocol and/or user decided to not wire that up, so it may be best if this was to be implemented that it can handle that possibility.

@lalamper  were you able to make the suggested changes and fix build errors?

**Comment by tananaev** [comment]
I believe this can be implemented using computed attributes.

**Comment by tsmgeek** [comment]
Based on current implementation of Computed Attributes
Event
`ignition ? (ignition == true && power >= 13 ? 'engineStarted':'engineStopped') : power >= 13 ? 'engineStarted':'engineStopped'`
This would cause a constant engineStopped event to be fired.

I still do not think it could work as it needs to compare the last position to the current one to see the transition happen. This could go wrong for protocol decoders like eelink that only partially populate the attributes when they get event from tracker.

**Comment by leifnel** [comment]
This won't work with cars that automatically stop the engine at standstills like red lights and congestions.

But of cause that is not a reason for not building this feature, as long as it is optional.

**Comment by tsmgeek** [comment]
@lalamper have you been able to fix the build issues and update

**Comment by lalamper** [comment]
@tsmgeek 
Hi,
Sorry, no, I had no time for this project, I was alone without any useful support.

**Pull request closed without merging**
