### PR TITLE
New Protocol Implementation

### PR DESCRIPTION
**Pull request by sake402**
Hi.
I added two protocol implementation for our GPS Tracker device.
Please have a look.

### CODE REVIEW

**Comment by sake402** [comment]
Hi Anton.
Sorr

**Comment by tananaev** [comment]
Make code look the same as existing code.

**Comment by sake402** [comment]
Hi Anton.
Please see the file modifications.
If there is any other thing, please let me know

**Comment by tananaev** [comment]
There are too many issues to comment. Unfortunately we won't be able to merge it in the current state. If you are interested please fix everything (formatting, spacing, indentation, naming etc etc). Also, year is not 2015.

**Pull request closed without merging**
