### PR TITLE
Add leafspy app protocol and decoder

### PR DESCRIPTION
**Pull request by jesserockz**
This PR adds a protocol and decoder to decode the live data that can be sent from the [LeafSpy Pro](http://www.electricvehiclewiki.com/wiki/leaf-spy-pro/) application which pulls information from the OBD port of a Nissan Leaf.

### CODE REVIEW

**Comment by tananaev** [comment]
Please make sure you include at least one unit test. Also, do you have a link to protocol/format documentation?

**Comment by jesserockz** [comment]
Hi Anton, Thanks for taking a look. 
Documentation for the app is available [here](http://www.leafspypro.com/wp-content/uploads/2017/09/LeafSpy-Help-1_2_1-iOS.pdf) with server data details on pages 39-40. 
Will get a/some tests in when I can next.

**Comment by tananaev** [comment]
Documentation says that lat/lon should be in the DD MM.MMM format.

**Comment by jesserockz** [comment]
I believe that is the CSV file format, but the http client always sends decimal format

```
Lat=xxx.xxxxx
Long=xxx.xxxx
```

**Comment by tananaev** [comment]
But doc says it should be the same format. Is the documentation incorrect?

**Comment by jesserockz** [comment]
Im not sure. Im just a user of the app and my local server always receives decimal format.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
