### PR TITLE
Whatsapp

### PR DESCRIPTION
**Pull request by AlessandroSantos**

### CODE REVIEW

**Comment by AlessandroSantos** [comment]
Adicionado suporte ao WhatsApp

**Comment by BIhab** [comment]
Hi, 
Interesting PR, do you have a screenshot on how the notification looks like?

**Comment by wendellbatera** [comment]
What parameters to pass in the traccar.xml file to install evolutionv2, nothing comes of it, can anyone help?

**Comment by tananaev** [comment]
@wendellbatera why are you asking here? Please only post in the relevant channels. And also don't duplicate your questions.

**Comment by wendellbatera** [comment]
Right. I want help if possible?

**Pull request closed without merging**
