### PR TITLE
Fix Summary export template

### PR DESCRIPTION
**Pull request by Abyss777**
Fix broken Summary template and reverted header line height (make consistent with others)

image

### CODE REVIEW

**Comment by Abyss777** [comment]
Sorry, all three had problems.

- Made header height double (like it was before)
- Made font size consistent (header 11 and lines 10)
- Reverted step out in brief 

image

image

image

**Comment by Abyss777** [comment]
Oh, I see another problem on screenshot

**Comment by Abyss777** [comment]
Hope it is final. Fixed vertical alignment. Sorry for taking your time.


image

image

image

**Comment by netluca1** [comment]
hi good job but I think we should add the possibility 'to add a header / logo.

**Comment by netluca1** [comment]
hi good job but I think we should add the possibility 'to add a header / logo.

**Comment by tananaev** [comment]
Merged, thanks. Can't really see the files, but I trust you fixed it.

**Pull request merged**
