### PR TITLE
Add UDP support for GPSLogger and OpenGTS

### PR DESCRIPTION
**Pull request by AuroraRAS**
You can select the UDP mode in GPSLogger now.

Signed-off-by: AuroraRAS <chplee@gmail.com>

### CODE REVIEW

**Comment by tananaev** [comment]
Please include unit tests. Is the format completely different for UDP?

**Comment by AuroraRAS** [comment]
> Please include unit tests. Is the format completely different for UDP?

mostly different. They are shared $GPRMC field, but not other.

**Comment by tananaev** [comment]
If it's NMEA, can't we just use T55 protocol for it?

**Comment by AuroraRAS** [comment]
it's complex message, include account and device id. port 5005 can't handle it.

**Comment by AuroraRAS** [comment]
You are right, port 5005 is working fine.

**Pull request closed without merging**
