### PR TITLE
Add support to custom event fowarding

### PR DESCRIPTION
**Pull request by RodolfoSilva**
Just like #1534 added support for position fowarding, this PR add support for event fowarding withou extra changes to traccar code, so people can plug their own handlers for events.

### CODE REVIEW

**Comment by tananaev** [comment]
The custom handler, that you are referring to, has been removed, as far as I know. Can you please explain your use case. I feel like if you want something custom, you can have an external script that would take JSON from standard forwarder and convert it to whatever you need.

**Comment by RodolfoSilva** [comment]
The custom handler is still in the code (https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/BasePipelineFactory.java#L160-L171). 

I implemented this handler so I can use protocols other than HTTP to forward events. I'm actually using MQTT, but this handler is generic and could be used with any protocol.

**Comment by tananaev** [comment]
But someone would still have to implement that other handler, right?

**Comment by RodolfoSilva** [comment]
I can also add the protocol specific code for MQTT.

**Comment by tananaev** [comment]
That would make more sense, but I'm also not convinced we need the whole `EventForwarderManager`. Maybe an interface with different implementations is a better option.

**Comment by RodolfoSilva** [comment]
Hey @tananaev, thanks for feedback.

How about I create a new `NotificatorMQTT` to handle events and a `MQTTDataHandler` to handle positions, so we can take advantage of the structure already in place?

And I would also, add the MQTT connection params to the `traccar.xml`.

**Comment by tananaev** [comment]
It's already in place for both positions and events. There's forwarding for both.

**Comment by J-Paul0815** [comment]
@tananaev 
Forwarding the position data via MQTT is exactly what I am looking for. Is there more information on how and what needs to be entered in the configuration? Thanks in advance.

**Comment by tananaev** [comment]
@J-Paul0815, I don't really understand your question. There is no MQTT support for it yet, so what configuration are you talking about?

**Comment by J-Paul0815** [comment]
@tananaev @
Sorry Anton, I must have misunderstood the previous posts. I am looking for a way to get current position data in Iobroker.

**Pull request closed without merging**
