### PR TITLE
Fix error with protocol version reporting from Traccar server to eeLink device

### PR DESCRIPTION
**Pull request by casswarry0**
As discussed via mail.

### CODE REVIEW

**Comment by tananaev** [comment]
Please provide documentation and also add some tests.

**Comment by casswarry0** [comment]
Attached you find the most recent protocol specification from eeLink.

The code changes are only minor and are commented inline like the rest of the code. You can reuse
existing tests.

Am Sonntag, dem 21.11.2021 um 09:48 -0800 schrieb Anton Tananaev:

**Comment by tananaev** [comment]
You can't attach files to an email to GitHub. As for tests, I'm expecting a test that would test your new functionality.

**Comment by casswarry0** [comment]
Ah, I didn't know that. But I sent you the protocol already. Have you looked at the patch? I think it is pretty obvious what the code does. I tested it on my Traccar server and the communication with the GPT46 works now without errors. So I guess the patch works fine.

I don't know how to write a test for Traccar but I suppose you can do that just fine with the log entries I sent you. If you don't like the patch feel free to close the pull request.

21.11.2021 11:01:47 Anton Tananaev ***@***.***>:

**Comment by tananaev** [comment]
Please provide the protocol documentation here, so we have all relevant information in one place.

If you don't know how to write tests, please provide at least samples with expected values.

**Comment by casswarry0** [comment]
Here is the most recent [eeLink protocol version 2.2(A4)](https://github.com/traccar/traccar/files/7577739/eeLink.Device.Protocol.V2.2._A4_.pdf).

**Comment by casswarry0** [comment]
This is an excerpt from the Traccar log after applying the patch. The data is now decoded correctly.
```
2021-11-22 00:35:15  INFO: [02c6c809] connected
2021-11-22 00:35:22  INFO: [02c6c809: eelink < 12.153.230.185] HEX: 67670100180896086528404575474801000221222100020452007108fe
2021-11-22 00:35:22  INFO: [02c6c809: eelink > 12.153.230.185] HEX: 67670100080896619ad7ba0100
2021-11-22 00:35:32  INFO: [02c6c809: eelink < 12.153.230.185] HEX: 67671200590895619ad7ae810395eba1f4023bb4018e000000000008030136019a8002800207545a0f000000dd1>
2021-11-22 00:35:32  INFO: [02c6c809: eelink > 12.153.230.185] HEX: 67671200020895
2021-11-22 00:35:32  INFO: [02c6c809] id: 865284045754748, time: 2021-11-22 00:35:10, lat: 33.42046, lon: -111.76680, course: 0.0
2021-11-22 00:36:12  INFO: [02c6c809: eelink < 12.153.230.185] HEX: 67671200590897619ad7ea810395eba1f4023bb4018e000000000008030136019a8002800207545a0f000000dd1>
2021-11-22 00:36:12  INFO: [02c6c809: eelink > 12.153.230.185] HEX: 67671200020897
2021-11-22 00:36:12  INFO: [02c6c809] id: 865284045754748, time: 2021-11-22 00:36:10, lat: 33.42046, lon: -111.76680, course: 0.0
2021-11-22 00:37:12  INFO: [02c6c809: eelink < 12.153.230.185] HEX: 67671200590898619ad826810395eba1f4023bb4018e000000000008030136019a8002800207545a0f000000dd1>
2021-11-22 00:37:12  INFO: [02c6c809: eelink > 12.153.230.185] HEX: 67671200020898
2021-11-22 00:37:12  INFO: [02c6c809] id: 865284045754748, time: 2021-11-22 00:37:10, lat: 33.42046, lon: -111.76680, course: 0.0
```

**Comment by tananaev** [comment]
All you samples in the log are cut, probably by your text editor. Also, can you please provide corresponding expected values for testing.

**Comment by casswarry0** [comment]
Ok, I edited the above log excerpt and it is now the full length. I also matched the log entry:
```
2021-11-22 06:09:56  INFO: [b8ace602: eelink < 12.153.230.162] HEX: 67671200560a60619b2623910395ec22f4023c08017c0000000008cc32e5636f71e408010136019a8002800207545a0f000000dd13f6b106890fe400000000000000130c450c450009000414000000000000070000000000000002
2021-11-22 06:09:56  INFO: [b8ace602: eelink > 12.153.230.162] HEX: 67671200020a60
2021-11-22 06:09:56  INFO: [b8ace602] id: 865284045754748, time: 2021-11-22 06:09:55, lat: 33.42053, lon: -111.76675, course: 0.0
```
with the values of the web interface:
```
Zeit 2021-11-22 05:09:55
Breitengrad 33° 25.232067' N
Längengrad 111° 46.005067' W
Gültig Ja
Genauigkeit 0.00 km
Höhe 380
Geschwindigkeit 0.0 kn
Richtung N
Protokoll eelink
Index 2656
Satelliten 8
Status 1673
Batterie 4.07 V
Adc0 0
Adc1 0
Kilometerzähler 0.02 km
Schritte 9
Temp1 20
Humidity 0
Illuminance 0.03
Co2 0
Temp2 0
Distanz 0.00 km
Gesamtdistanz 12026.37 km
Bewegung Nein
```

**Comment by tananaev** [comment]
Looks like your code breaks existing test cases.

**Comment by tananaev** [comment]
I'm not sure I understand your comment. Your change is breaking other devices.

**Comment by casswarry0** [comment]
The problem is this test:
```
verifyNotNull(decoder, binary("6767**14**004F14B0E68CAFE5**8A**A8E68AA5E8ADA621E5B9BFE4B89CE79C81E6**B7B1**E59CB3E5B882E58D97E5B1B1E58CBAE696B0E8A5BFE8B7AF3138EFBC88E8B79DE5AE87E998B3E5A4A7E58EA63230E7B1B3EFBC89"));
```
Counting the bytes it is a WARNING package. The Mask = 8A = 10001010, after reading 11 bytes (BSID0) and 7 bytes (BSID2) the LTE cell info should follow with RAT = B7 and NoC = B1. These values look strange. Even when B7 is the warning type the value makes no sense. So this package must be from a really old protocol version.

**Comment by casswarry0** [comment]
I reverted the changes to POSITION data type. But there was an error when creating the response to the LOGIN package. The protocol version was Byte but has to be Short (already in version 2.0 of the protocol). This caused the eeLink device to not switch to compatible mode and therefore sending the LTE cell info.

**Comment by tananaev** [comment]
So, what can we do about it?

**Comment by casswarry0** [comment]
I have updated the patch. It works now on my Traccar server with the GPT46 and your test suite also passes.

23.11.2021 14:00:23 Anton Tananaev ***@***.***>:

**Comment by tananaev** [comment]
But you said there's still some problem.

**Comment by casswarry0** [comment]
The problem is solved with the updated patch. Now Traccar works with the GPT46 because it switches the GPT46 to compatible mode and therefore the GPT46 never sends LTE cell info. Old eeLink devices still work since they don't know about the new mode introduced with protocol version 2.2.

**Comment by tananaev** [comment]
I'm very confused now with this PR. Now instead of changing decoding you are changing response format. Wouldn't it break old devices?

**Comment by casswarry0** [comment]
With protocol version 2.2 eeLink added LTE cell info to POSITION data type. The first version of the PR added the LTE cell info to the POSITION data type which broke old devices. So I looked into the LOGIN package where the following is stated:
Name | Bytes | Description
--- | --- | ---
Time | 4 | Current time (UTC) in the server
Version | 2 | Protocol version (see note 1) — 0x01: default
PS Action | 1 | Param-set action mask (see note 2)

This is the same definition in protocol version 2.0 and 2.2 but in version 2.2 note 1 was amended:

> *Protocol version” is the version of the protocol supported by server.
> If it is different from the protocol version in device, device will generate
> and transmit only the compatible packages to server.
> **0x01: The server doesn’t support any extension (in compatible mode);**
> **0x02: The server supports LTE data (see Section 3.6 POSITION);**

The last two lines where added. Then I checked the code in Traccar server which was:
```
            if (type == MSG_LOGIN) {
                content.writeInt((int) (System.currentTimeMillis() / 1000));
                content.writeByte(1); // protocol version
                content.writeByte(0); // action mask
            }
```
This was obviously wrong, protocol version is 2 bytes, so I changed the code to:
```
            if (type == MSG_LOGIN) {
                content.writeInt((int) (System.currentTimeMillis() / 1000));
                content.writeShort(1); // protocol version
                content.writeByte(0); // action mask
            }
```
After that change the GPT46 was switching to compatible mode and was not sending the LTE cell info which was breaking the old devices. Since the definition has not changed since protocol version 2.0 and 0x01 is the default value this should not affect old devices.

**Comment by casswarry0** [comment]
The commit 45bbb7a is not supposed to show up here. I wanted to make a separate PR for the additional status codes but Github added it right here. Is there a way to remove it here?

**Comment by tananaev** [comment]
> Since the definition has not changed since protocol version 2.0 and 0x01 is the default value this should not affect old devices.

What about pre-2.0?

**Comment by casswarry0** [comment]
2.0 is the earliest I have and according to the specs the one Traccar is compatible with.

23.11.2021 23:38:36 Anton Tananaev ***@***.***>:

**Comment by tananaev** [comment]
Here's an old version of eelink protocol:

[EELINK_Terminal_Communication_Protocol_V1.8.4_EN.pdf](https://github.com/traccar/traccar/files/7597690/EELINK_Terminal_Communication_Protocol_V1.8.4_EN.pdf)

Looks like format is different, so I guess we can merge your change.

Can you please revert your last commit.

**Comment by casswarry0** [comment]
Can't you merge only the the first 3 commits and ignore the last commit 45bbb7a? Because I want to keep the last commit in my fork.

**Comment by tananaev** [comment]
I can only merge a branch. Just move your last commit to a separate branch.

**Comment by casswarry0** [comment]
I have moved my last commit to another branch.

**Comment by tananaev** [comment]
Merged, thank you.

**Pull request merged**
