### PR TITLE
fix: AMQP auto close connection

### PR DESCRIPTION
**Pull request by RodolfoSilva**
Currently, the AMQP connection is being closed after the completion of block execution.
I made a mistake in my last PR #5136.

### CODE REVIEW

**Comment by tananaev** [comment]
So where do you close connection then?

**Comment by tananaev** [comment]
But you're removing it from the try-with-resources statement. I'm asking about your new code.

**Comment by RodolfoSilva** [comment]
Today, this will not be closed. Is there a place where I can add a shutdown method? I haven't seen this in the EventForwarder and PositionForwarder interfaces.

**Comment by tananaev** [comment]
In other places we close connection after each message, like you had before. That's why I'm asking.

**Comment by RodolfoSilva** [comment]
This is not how RabbitMQ works. 

Repeatedly opening and closing connections for each message can significantly reduce. It can also put unnecessary load on the RabbitMQ server, potentially affecting its performance or stability.

It's generally recommended to establish a connection when the application starts up, and keep it open for as long as it's needed. This allows you to send many messages (potentially millions) over the same connection, reducing the per-message overhead and thus increasing the overall efficiency and performance.

In addition, RabbitMQ's protocol provides for certain optimizations like publishing confirmations and delivery tags that rely on maintaining a stable connection.

Te RabbitMQ client provide an automatic connection recovery to handle temporary network failures.

However, I could use the `Runtime.addShutdownHook()` to close the connection when the app is stopping. What do you think?

**Comment by tananaev** [comment]
I don't think we need `Runtime.addShutdownHook()`. The OS will close all the network connections if needed. I was more worried about failed connections and retried. Is it handed automatically by the library? If yes, what's the policy?

**Comment by RodolfoSilva** [comment]
@tananaev The official documentation from library says that library will handle this connection recovery process automatically by default:

[RabbitMQ Java Client Documentation](https://www.rabbitmq.com/api-guide.html#recovery)
`ConnectionFactory` API documentation: [ConnectionFactory (RabbitMQ Java Client API Guide)](https://rabbitmq.github.io/rabbitmq-java-client/api/current/com/rabbitmq/client/ConnectionFactory.html)

image

Should I remove the `ShutdownHook`?

**Comment by tananaev** [comment]
Yeah, let's remove the `ShutdownHook` then. Please create the connection in the constructor then.

**Comment by RodolfoSilva** [comment]
Done.
The connection is already created inside the AmqpClient constructor.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
