### PR TITLE
Bugfix/ldap user login

### PR DESCRIPTION
**Pull request by grmt**
Logging in with an ldap user failed with latest master

### CODE REVIEW

**Comment by tananaev** [comment]
Can you please include only the changes related to this PR. Also provide some context on why it's not working.

**Comment by grmt** [comment]
tc_users table is empty
ldap properly configured
login with valid ldap_user

This is the response you receive in the ui:
ERROR: column "password" of relation "tc_users" does not exist
  Position: 22 - PSQLException (... < QueryBuilder:460 < DatabaseStorage:57 < DataManager:259 < ...)

tracker-engine will try to create user in db, but fails because the Request has an extra "password" column.

With respect to the unrelated changes, you could merge #4811 or otherwise I'll try to remove them tonight.

**Comment by grmt** [comment]
"Now" rather than "tonight".  Time well spent on mastering the git command line and learning about git interactive rebase and forced push

**Comment by tananaev** [comment]
https://github.com/traccar/traccar/pull/4811 is not ready to be merged yet. Not all my comments are addressed and there are also some unrelated changes that need to be removed.

As for the fix here, I don't think it's right. Password field should be excluded using `@QueryIgnore`, not explicitly. Please investigate why it's not excluded.

**Comment by tananaev** [comment]
Please try this fix https://github.com/traccar/traccar/commit/23bbb48eaf69db1c858a7f027d9f7a2fba8796ea.

**Comment by grmt** [comment]
tested it and works fine
so will close this issue

**Comment by grmt** [comment]
thank you

**Pull request closed without merging**
