### PR TITLE
Jt701 implementation

### PR DESCRIPTION
**Pull request by laudarch**
I have done a quick implementation for Jt701, this has status and alarms that conflict with Jt600 when you try to combine them

### CODE REVIEW

**Comment by tananaev** [comment]
If those are the only conflicts, I don't think we need to duplicate everything else.

**Comment by laudarch** [comment]
> If those are the only conflicts, I don't think we need to duplicate everything else.

Am looking at adding the other missing features for JT701, documentation is here https://we.tl/t-uTZa9e74XX

**Comment by tananaev** [comment]
Can you please elaborate on the conflicts.

**Comment by laudarch** [comment]
> Can you please elaborate on the conflicts.

I just updated the comment

**Comment by tananaev** [comment]
Unfortunately it doesn't answer my question - why do you want to duplicate the rest of the code?

**Comment by laudarch** [comment]
> Unfortunately it doesn't answer my question - why do you want to duplicate the rest of the code?

What do you suggest?

**Comment by tananaev** [comment]
I suggest reusing the code.

**Comment by laudarch** [comment]
> I suggest reusing the code.

let me attempt and test

**Comment by laudarch** [comment]
Reuse is not working bro, tried extending even, am going to implement JT707A because I have a need for it, might have to visit this later unless you can fix it.

**Comment by tananaev** [comment]
OK, closing this for now. Feel free to send a new PR later if you find a way.

**Pull request closed without merging**
