### PR TITLE
Add Base Adresse Nationale reverse geocoder

### PR DESCRIPTION
**Pull request by oliv3**

### CODE REVIEW

**Comment by tananaev** [comment]
I don't see anything about API key in the documentation. Is it required? How to get one? Any documentation?

**Comment by oliv3** [comment]
It will be possible to get a key in the future, but it will be optional and only for usage tracking purposes.
There is no way to request one at the moment since this feature is not in production yet.
I was confirmed there will be one someday, so this parameter can safely be ignored for now - done by anticipation.
Limitations are 10 requests per second per IP address.

**Comment by oliv3** [comment]
https://adresse.data.gouv.fr/api

**Comment by tananaev** [comment]
OK, if it's not available at the moment, I think we should remove it from the code.

**Comment by oliv3** [comment]
Is commented ok ?

**Comment by tananaev** [comment]
No, it has to be removed.

**Comment by oliv3** [comment]
Hi, code has been removed and branch rebased.

**Comment by tananaev** [comment]
Merged, thanks.

**Comment by jpmens** [comment]
It should be clarified in the documentation that this API returns data for France only.

> ou la France entière

[/via](https://adresse.data.gouv.fr/download)

**Comment by oliv3** [comment]
Indeed. Whole France, including D.O.M.s and T.O.M.s e.g. Kourou, Guyana:
```https://api-adresse.data.gouv.fr/reverse/?lat=5.169189&lon=-52.6813537```
Website is not on Github so I'll leave this to @tananaev .

**Pull request merged**
