### PR TITLE
Odometer in reports clean

### PR DESCRIPTION
**Pull request by ckrey**
Implements Odometer in Summary, Trips, and Stops Reports traccar/traccar-web#652
relies on corresponding PR in traccar/traccar-web

Replaces #3848

### CODE REVIEW

**Comment by tananaev** [comment]
Merged, thanks.

**Comment by tananaev** [comment]
Looks like temples got broken:

https://www.traccar.org/forums/topic/templates-remaining-in-exported-report/

And the formatting in templates also inconsistent.

Can you please fix it.

**Comment by ckrey** [comment]
Sorry, I now understand I didn't adjust the "lastCell" attribute when changing the templates

**Comment by tananaev** [comment]
I don't understand one thing. Have you actually checked that it works before sending pull request?

**Pull request merged**
