### PR TITLE
Possibility to obtain information about the "neighborhood" in Google's reverse geocoding.

### PR DESCRIPTION
**Pull request by Turbovix**
Added the possibility of obtaining information about the "**neighborhood**" in Google's reverse geocoding.

Before:
197-223 R. Our Lady of the Rosary, Vila Velha, ES, BR

After:
197-223 R. Our Lady of the Rosary, "**Santa Paula II**", Vila Velha, ES, BR, 29126250

Note:
* In Brazil this information is very important
* You need to update the documentation for the "geocoder.format" parameter, including "% n"

### CODE REVIEW

**Comment by tananaev** [comment]
What about other geocoders? For example Nominatim?

**Comment by Turbovix** [comment]
I'm very selfish, huh? I just thought about my use case!
I'll check the others!

**Comment by tananaev** [comment]
You don't need to check all, but at least Nominatim as one of the most popular options.

**Comment by Turbovix** [comment]
Anton, In the case of the service of Nominatim, it is already suitable in Class "NominatimGeocoder", according to the information code below:

`<searchresults timestamp="Tue, 19 Dec 17 21:33:22 +0000" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="rua nossa senhora do rosario,santa paula,vila velha," polygon="true" exclude_place_ids="122975469" more_url="http://nominatim.openstreetmap.org/search.php?q=rua+nossa+senhora+do+rosario%2Csanta+paula%2Cvila+velha%2C&polygon=1&exclude_place_ids=122975469&addressdetails=1&format=xml&accept-language=pt-BR%2Cpt%3Bq%3D0.9%2Cen-US%3Bq%3D0.8%2Cen%3Bq%3D0.7"> <place place_id="122975469" osm_type="way" osm_id="228663008" place_rank="26" boundingbox="-20.4180482,-20.4162186,-40.3385748,-40.3359672" polygonpoints="[["-40.3385748","-20.4180482"],["-40.3384263","-20.417944"],["-40.3380985","-20.4177175"],["-40.33773","-20.4174555"],["-40.3373903","-20.4172171"],["-40.3370401","-20.4169713"],["-40.3366985","-20.4167316"],["-40.3363392","-20.4164796"],["-40.3359672","-20.4162186"]]" lat="-20.4172171" lon="-40.3373903" display_name="Rua Nossa Senhora do Rosário, Santa Paula II, Região 05 - Grande Jucu, Vila Velha, Microrregião Vitória, Região Metropolitana da Grande Vitória, Mesorregião Central Espírito-Santense, Espírito Santo, Região Sudeste, 29126-902, Brasil" class="highway" type="residential" importance="0.825"> `
`<road>Rua Nossa Senhora do Rosário</road>`
 **`<suburb>Santa Paula II</suburb>`**
` <city_district>Região 05 - Grande Jucu</city_district>`
` <city>Vila Velha</city>`
` <county>Microrregião Vitória</county>`
` <state_district>Mesorregião Central Espírito-Santense</state_district>`
` <state>Espírito Santo</state>`
` <postcode>29126-902</postcode>`
` <country>Brasil</country>`
` <country_code>br</country_code> `
`</place>
``</searchresults>
`
```

Class - NominatimGeocoder.java 

if (result.containsKey("suburb")) {
                address.setSuburb(result.getString("suburb"));
            }
```

**Comment by tananaev** [comment]
OK, so I guess we can re-use suburb for Google as well?

**Comment by Turbovix** [comment]
In Google I tested with suburb but he himself the name of the city!

**Comment by tananaev** [comment]
Well, that sounds wrong. Can you please provide original and parsed data for both Google and Nominatim?

**Comment by Turbovix** [comment]
Anton, you see that in the case of Google, it captures the data as described in "GoogleGeocoder.java":

```
case "political":
                             address.setPolitical (value);
                             break typesLoop;
```

{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "197-223",
               "short_name" : "197-223",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Rua Nossa Senhora do Rosário",
               "short_name" : "R. Nossa Sra. do Rosário",
               "types" : [ "route" ]
            },
          `  **
{
               "long_name" : "Santa Paula II",
               "short_name" : "Santa Paula II",
               "types" : [ "political", "sublocality", "sublocality_level_1" ]
            },
**`
            {
               "long_name" : "Vila Velha",
               "short_name" : "Vila Velha",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Vila Velha",
               "short_name" : "Vila Velha",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Espírito Santo",
               "short_name" : "ES",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "Brasil",
               "short_name" : "BR",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "29124",
               "short_name" : "29124",
               "types" : [ "postal_code", "postal_code_prefix" ]
            }
         ],
         "formatted_address" : "R. Nossa Sra. do Rosário, 197-223 - Santa Paula II, Vila Velha - ES, Brasil",
         "geometry" : {
            "bounds" : {
               "northeast" : {
                  "lat" : -20.4172656,
                  "lng" : -40.3373654
               },
               "southwest" : {
                  "lat" : -20.417498,
                  "lng" : -40.3376983
               }

**Comment by tananaev** [comment]
I need to see the difference. And you need to know what's expected.

**Comment by Turbovix** [comment]
Anton, tell me one thing, because the server running on Netbeans can not get the address? I'm having to do the testing on a server, which is pretty hard work.
captura de tela de 2017-12-19 20-53-58

**Comment by Turbovix** [comment]
I've adjusted the "defaut.xml" settings to use the NOMINATIM settings, but that's the result I have.

`<entry key='geocoder.enable'>true</entry>`
`<entry key='geocoder.type'>nominatim</entry>`
`<entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>`

captura de tela de 2017-12-19 21-40-17

**Comment by tananaev** [comment]
I believe Nominatim free server blocks Traccar. Probably people overused it.

**Pull request closed without merging**
