### PR TITLE
Try to fix mysql 8 error on new group creation

### PR DESCRIPTION
**Pull request by metacreo**
Try to fix mysql 8 error on new group creation

### CODE REVIEW

**Comment by joystickjockey** [comment]
This did not fix the issue unfortunately.
I've patched it, build it and tested it and still have the issue.

**Comment by metacreo** [comment]
ok... what error (after patch) you see when calling group api?

**Comment by joystickjockey** [comment]
Hi mate I get below error:
api

**Comment by joystickjockey** [comment]
I've made changes as pe below:
Screenshot 2022-05-25 203847

**Comment by metacreo** [comment]
show me my.cnf config please from /etc/mysql/ or /etc/my.cnf

**Comment by joystickjockey** [comment]
#
# The MySQL database server configuration file.
#
# You can copy this to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
# 
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#

!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/

**Comment by metacreo** [comment]
/etc/mysql/mysql.conf.d/mysqld.cnf this

**Comment by joystickjockey** [comment]
#
# The MySQL database server configuration file.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

# Here is entries for some specific programs
# The following values assume you have at least 32M ram

[mysqld]
#
# * Basic Settings
#
user		= mysql
# pid-file	= /var/run/mysqld/mysqld.pid
# socket	= /var/run/mysqld/mysqld.sock
# port		= 3306
# datadir	= /var/lib/mysql


# If MySQL is running as a replication slave, this should be
# changed. Ref https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_tmpdir
# tmpdir		= /tmp
#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address		= 127.0.0.1
mysqlx-bind-address	= 127.0.0.1
#
# * Fine Tuning
#
key_buffer_size		= 16M
# max_allowed_packet	= 64M
# thread_stack		= 256K

# thread_cache_size       = -1

# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched
myisam-recover-options  = BACKUP

# max_connections        = 151

# table_open_cache       = 4000

#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
#
# Log all queries
# Be aware that this log type is a performance killer.
# general_log_file        = /var/log/mysql/query.log
# general_log             = 1
#
# Error log - should be very few entries.
#
log_error = /var/log/mysql/error.log
#
# Here you can see queries with especially long duration
# slow_query_log		= 1
# slow_query_log_file	= /var/log/mysql/mysql-slow.log
# long_query_time = 2
# log-queries-not-using-indexes
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
# server-id		= 1
# log_bin			= /var/log/mysql/mysql-bin.log
# binlog_expire_logs_seconds	= 2592000
max_binlog_size   = 100M
# binlog_do_db		= include_database_name
# binlog_ignore_db	= include_database_name

**Comment by metacreo** [comment]
nice
after line 'mysqlx-bind-address = 127.0.0.1' add lines:

sql_mode                       = ""
init_connect                   = "SET NAMES 'utf8'"
character_set_server           = utf8mb4
collation_server               = utf8mb4_unicode_ci

then restart mysql server and traccar
like (systemctl stop mysql && systemctl start mysql)

**Comment by joystickjockey** [comment]
Hi mate I made the changes as per below, stopped traccar, restarted mysql, started traccar but still get the same error
changes

**Comment by joystickjockey** [comment]
Hi mate, still the exact same error. Thanks for assisting.

**Comment by metacreo** [comment]
leave mysql config with added lines and try edit traccar.xml
change db connection entry to:
`<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>`

**Comment by joystickjockey** [comment]
ive made the changes but still have the same error.

**Comment by tananaev** [comment]
Can someone rename it to something `tmp_groups` and try? Why struggle with quotation issues.

**Comment by joystickjockey** [comment]
If I rename it to tmp_groups in DatabaseStorage.java i get error below

error

**Comment by tananaev** [comment]
https://github.com/traccar/traccar/commit/8e8a435cea0ea44dfcb20b45dcbb881b87361676

**Comment by joystickjockey** [comment]
Ignore my response, it is working now. I've updated the project and tested it. working fine now thanks.

**Pull request closed without merging**
