### PR TITLE
notifications refactor, generic internal representation

### PR DESCRIPTION
**Pull request by ivanfmartinez**
@tananaev  what you think about this instead of #3823 

It's just a first step without making changes in DB and UI.

### CODE REVIEW

**Comment by tananaev** [comment]
@Abyss777, can you please review the code? I had a brief look and it mostly looks fine except for some minor issues, but you have more experience with notifications.

**Comment by Abyss777** [comment]
I do not see an issues in logic. May be some minor issues with naming and style.

Do we have any reason to make other two types of notifications "replaceable" ?

**Comment by ivanfmartinez** [comment]
One replacement for standard javamail is the use of SNS/SES : https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notifications-via-sns.html its very easy to use and can be defined just by the permissions for the EC2 machine, without manual configuration for user/password.

The only one that I cannot see a replacement is the web notification, but its easier to make all using same logic and in the future if the UI is changed will be easy to replace the logic.

**Comment by ivanfmartinez** [comment]
How do you think the configurations can be done to make possible to use other notifications ? 

I want to move my mqtt processing logic to use this notificators because will make possible to work with all traccar events.

**Comment by tananaev** [comment]
We don't really need to come up with examples on replacements. I think it's just a good idea to have flexible options. Also, ideally we need to think of a flexible way to add new notification types (e.g. chat or push notifications).

I don't really see any benefit of MQTT. People keep talking about it, but no-one can properly explain why we need it. I see it only as an extra complexity. Will a person with limited technical knowledge be able to set it up? I doubt it.

**Comment by ivanfmartinez** [comment]
MQTT in an internal network is very easy. Just put the server on and point your publishers and subscribers.  No username/password, you decide your topics, I think is very easy for any user.

Using this integration I can make my openhab know when I'm at home without making traccar talk to my openhab, traccar just publish the states and openhab read the states in a unified bus.

Probably like you I don't like the idea of MQTT as public and available on the internet (which many people want to do), this will make more complicated, needing passwords, with many headaches for security.

Apps like mqttwarn https://github.com/jpmens/mqttwarn can translate data published in the topics to many other services without need to code inside.

**Comment by Abyss777** [comment]
I would leave everything as is, just make web/email/sms classes replaceable, like `sms.manager.class`.
Renaming it is not a big deal.

Now we have three essential classes of notification:
- Web - online, for most of all notifications, just online
- Email - not urgent information, mostly for archive
- Sms - urgent type of notifications

Do we need an another class of notifications? Not transport but class.

There are a lot of wanted transports (push, telegram, jabber, may be some ECM) but I believe in most cases 3 classes enough.

Just thoughts, may be in future make it possible to select transports for every class in user/server attributes.

**Comment by ivanfmartinez** [comment]
I think the user should decide which notification types it can use.

As an example here in Brazil the SMS providers has two options : promotional (less reliable) and transactional, the cost as different, delivery time and other things.

As a traccar user I want to define some notifications to be as sms_promotional and some as sms_transactional dependending of device, for some devices I want full reliablility for others it does not matter and I can use the cheaper.

The best provider for transactional is not the same as the transactional, if I can create as many notification types I want will be easy to implement the changes to support this .

Also I can consider telegram as reliable for urgent for some users/devices but not for others.

Please let the user decide which notification methods are better for each case.

**Comment by Abyss777** [comment]
We can remove web/email/sms from Notification object and add some string field like `transport`. One Notification will be responsible for one event and one transport.

I believe initial configuration will be a pain, user need to create lots of Notification objects to enable all.

**Comment by ivanfmartinez** [comment]
will be a lot of notification definitions but will make possible to a more granular configuration and expand to any number of transports.

Thinking about future I would suggest something like have two fields :

transport and options

mail    "EMPTY  OPTIONS"  - use default user email
mail    "something@domain" - use this specific email for this notification
sms   "EMPTY OPTIONS"  - use default user email
sms   "+111111" - use specific phone number.

Will be better if the transport class provides access to an json schema and the options can be a json based on the schema. 

We can have configuration like :
sms  { "type" : "transactional", "destination" : "+111111" }

The json appears to be difficult for users, but we can hide the json using this library : https://github.com/json-editor/json-editor  I have used it in some projects and works fine, I have the schema available on the webserver and the fields and created dynamically based on the schema file.

https://rawgit.com/jdorn/json-editor/master/examples/css_integration.html

**Comment by tananaev** [comment]
I completely agree with @Abyss777. It makes sense to have a flexible option to select transport.

I don't agree with last comment here. We already have use email and phone configuration. I believe that's enough and we don't need another option to set it. We just need to provide user model to specific notificator and it can extract whatever it needs to deliver notification (e.g. email or phone).

**Comment by Abyss777** [comment]
I just thought we can make this `transport` field comma-separated list, to not make users add a lot of Notification objects.

Also we need some API to enumerate currently available transports.

Have no idea for now how to configure unknown number of "notificators" in config file, may be also with friendly names.

**Comment by ivanfmartinez** [comment]
What you think about

    <entry key='notificator.types'>web,sms,mail,mqtt</entry>
    <entry key='notificator.sms.class'>className</entry>
    <entry key='notificator.mail.class'>className</entry>
    <entry key='notificator.mqtt.class'>className</entry>

I sugest also to pass the "type" for the class constructor, this will make possible to have also generic configuration for each notificator as 
    <entry key='notificator.mqtt.url'>tcp://....</entry>

**Comment by Abyss777** [comment]
Any news here?
There are so much requests of implementing different sms providers...

**Comment by ivanfmartinez** [comment]
I'm using this implementation on my server, the internal things are working fine. 
But I don't know how  the web interfaces interact with the model to make the UI changes.

This format permits to have multiple dynamic notificators. The SMS default notificator implementation also uses a generic SMSManager. And will be very simple to implement different SMS options.

**Comment by Abyss777** [comment]
UI later.

We need convert 3 fields web/mail/sms to one comma separated string like `transport`
And adjust your code to use list of transports from `notificator.types`

**Comment by ivanfmartinez** [comment]
If you make the changes in the database the changes in my code is just in the method that returns a set of notification transports : https://github.com/traccar/traccar/pull/3830/files#diff-8c3515db6a18762b9cee7586050fb5bcR73

and remove the old methods for SMS, MAIL and WEB.

**Comment by parveenkumardeeva** [comment]
Any update here?

**Comment by ljporter1723** [comment]
+1 vote for built in traccar notifications for push and especially mqtt.  @ivanfmartinez do you have step by step guide to implement your mqtt traccar code for a non coder? SMS and mail is next to useless.

**Comment by Abyss777** [comment]
Looks like there is no movement here.
I'm going to implement general approach discussed here if nobody is working on it.

**Comment by ivanfmartinez** [comment]
@ljporter1723  in the repo : https://github.com/ivanfmartinez/ivanfm-traccar-mqtt  you can just compile the code and add configurations from the README and you can send data to mqtt. I use it in my system, I have an script which get messages from mqtt and send to telegram. You can use https://github.com/jpmens/mqttwarn for this gateway

I have made all the changes I know how to do in the traccar code in the backend. As  I don't have the experience or time learn to make the UI or database changes.

I have made some changes in Apr/09, and no one commented about these. As the PR for traccar need to be exactly how @tananaev  wants, I will not make more changes without specific directions.

In my mind this part can be merged as it currently works without changes in current code / db. This make possible to people start testing and creating their own code for notifications, and more people help.

**Comment by ivanfmartinez** [comment]
@tananaev  the Null notification make easy for any place use notificators without checking if they exist or not. 

If  someone configure an notificator and it does not exist it will not give a null object, and the server will stay running fine without a lot of null checkings.

**Comment by Abyss777** [comment]
- I think it is better initialize `NotificatorManager` in `Context` like we do with all other managers.
- I think we do not need initialize two `SmppClient`. I believe we can use something like `Context.getNotificatorManager.getNotificator("sms") instead of `Context.getSmsManager()`

**Comment by Abyss777** [comment]
Or you have a reason for separate `SmsManager`?

**Comment by ivanfmartinez** [comment]
@Abyss777 where did you find two initiatilization for SmppClient ?

It is just instantiated in the Context.

The SMS is an special case where some devices receives commands by SMS. The SMSManager is the Interface that can be implemented by any SMS implemenation, and the SMSNotification uses this SMSManager implementation for sending SMS messsages.

The Notificator send notifications of events/positions to users, and the SMSManager sends messages to phone numbers.

To replace the SMS implementation the user should define sms.manager.class parameter with the class name for an SMSManager implementation.

**Comment by Abyss777** [comment]
@ivanfmartinez Sorry, you are right. `NotificationSms` initialized secondly and uses `SmsManager`.

Thanks for explanation. That's more clear now for me.

Do you use `NotificatorManager.getMail()` and `getSms()` only for testing? I believe we should test all configured notificators by list. (there might be other types, not only "mail" and "sms")

**Comment by Abyss777** [comment]
Please add the `changelog-3.18` to `changelog-master` and comment out `dropColumn`s from changelog-3.18 if schema migration goes OK. 

General logic is fine to me.

**Comment by parveenkumardeeva** [comment]
@tananaev Would you also consider this pull request with Netty 4?

**Comment by tananaev** [comment]
I don't think this pull request has anything to do with Netty.

**Comment by parveenkumardeeva** [comment]
No, I'm asking for Traccar v4.0 as I read your comments during Netty 4 development that you are going to release next version as Traccar 4.0

**Comment by tananaev** [comment]
That's not what you asked.

**Comment by parveenkumardeeva** [comment]
Sorry my bad, for not describing the question completely.

**Comment by tananaev** [comment]
If it's ready by the time we release then we'll include it. There is no specific plan for it.

**Comment by parveenkumardeeva** [comment]
Ok, Thanks.

**Pull request merged**
