### PR TITLE
[TELTONIKA] Fix OBD_SPEED - change kmh to knots

### PR DESCRIPTION
**Pull request by lukasha12**
[TELTONIKA] Fix OBD_SPEED - change kmh to knots.
Teltonika gives OBD_SPEED in km/h, Traccar wants in knots.
https://wiki.teltonika-gps.com/view/FMB_AVL_ID

### CODE REVIEW

**Comment by tananaev** [comment]
Please see conversations here:

https://github.com/traccar/traccar/pull/4542

**Comment by lukasha12** [comment]
Thanks Anton.  I have read. I think geduksy is right about the obd speed - the frontend expects values ​​in knots.  You can either change the frontend so that it doesn't convert from knots to km / h.  Or you can save data to the database in knots, then converting to km / h will give a good value.  I suggested /1,852 but the solution suggested by  geduksy - UnitsConverter.knotsFromKph (if this function exists in traccar) looks better.
Now it looks that:

**Comment by tananaev** [comment]
As I mentioned there, the correct fix I expect is to use km/h for OBD speed.

**Comment by lukasha12** [comment]
You're right, it will result in less computation.  Unfortunately, I have too little knowledge to make this fix.

**Pull request closed without merging**
