### PR TITLE
Update TrvProtocolDecoder.java

### PR DESCRIPTION
**Pull request by Nikutrax**
more ignore response

### CODE REVIEW

**Comment by Nikutrax** [comment]
No response for following IWAP Commands:
AP33
AP34
AP84
AP85

**Comment by Nikutrax** [comment]
all checks are failed - i don´t know

**Comment by tananaev** [comment]
It's telling you exactly what the problem is.

**Comment by Nikutrax** [comment]
Am is good, You can implement the pull Request !

Am 2024-09-27 16:39, schrieb Anton Tananaev:

**Comment by tananaev** [comment]
If you don't plan on fixing it, I'm going to close it for now.

**Pull request closed without merging**
