### PR TITLE
fixed message encoding

### PR DESCRIPTION
**Pull request by flocsy**
without this the received message is displayed as gibrish

### CODE REVIEW

**Comment by tananaev** [comment]
Can I see documentation for the protocol where it says it expects UTF-16?

**Comment by flocsy** [comment]
https://github.com/tananaev/traccar/files/213814/3g.elec.comm.protocol.docx here the example is UTF-16, and for the SMS command it's written that it's "GB232" charset, but the meaning even there is UTF-16.
However the final fix came when today I tested it with a real Q50 watch. Even an ASCII text was displayed as "boxes" until I changed the encoding to UTF-16, and then it appeared as intended.

**Comment by tananaev** [comment]
Can you point me to the specific example with UTF-16. I don't see anything in the document.

**Comment by flocsy** [comment]
33. Phrases Display set instruction
Platform to send:
[CS*YYYYYYYYYY*LEN*MESSAGE, phrase content]
Example:[SG*5678901234*0018*MESSAGE,**597D003100320033**]

**Comment by flocsy** [comment]
6. Send text messages
Platform to send:
[CS*YYYYYYYYYY*LEN*SMS, SMS number, the content of the message]
Example: [SG*8800000015*001C*SMS,00000000000,123ABC everybody good]
Terminal response:
[CS*YYYYYYYYYY*LEN*SMS]
Example:[SG*8800000015*0003*SMS]

Explanation: send a message to the mobile phone number with the command, the content of the message sent by **GB232 code**.

**Comment by tananaev** [comment]
Not sure how you determined that it's UTF-16. But even if it is, it doesn't include BOM, but your code does.

**Comment by flocsy** [comment]
screenshot from 2019-01-30 05-15-31
img_20190130_051244
screenshot from 2019-01-30 05-14-15
img_20190130_051127

**Comment by flocsy** [comment]
You're right, it works without the BOM as well, I changed that in the 2nd commit

**Comment by flocsy** [comment]
and about the other comment: message sending was added by me about a week ago, not sure how many used it since, probably I'm the only one today... So it might or might not work. Even if it will it won't work because of what we "understand" from the google-translated Chinese "documentation" but because we tried it. So choosing not to change the encoding will for sure not work on my watch (I guss that's 100% of the watches who use it currently) and maybe will work on other watches that didn't have this feature 2 weeks ago...

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
