### PR TITLE
Fixes passwordReset.vm template

### PR DESCRIPTION
**Pull request by lzkill**
Adds the reset-password endpoint to the reset link.

### CODE REVIEW

**Comment by tananaev** [comment]
Merged, thank you.

**Comment by lzkill** [comment]
Maybe injecting the *modern* word from the config (`web.url`) might be useful in the future when the legacy frontend is removed. What do you think?

**Comment by tananaev** [comment]
No. Once legacy app is removed, the modern app will be in the root folder.

**Comment by lzkill** [comment]
Exactly... At this moment one could keep `web.url=https:/xxx.yyy/modern`. When the legacy is removed it the only required would be make  `web.url=https:/xxx.yyy`. But for this to work the template needs not to contain `modern` in the link, only the `reset-password endpoint`.

**Comment by tananaev** [comment]
We would just need to change the template later.

**Comment by tananaev** [comment]
Good catch. Fixed. I guess it doesn't matter in terms of functionality.

**Pull request merged**
