### PR TITLE
adding Jetty JMX and connection statistics

### PR DESCRIPTION
**Pull request by jcardus**

### CODE REVIEW

**Comment by jcardus** [comment]
Is this going to be approved? The only reason I need this is to get the number of currently connected users

**Comment by tananaev** [comment]
There is no description why we need it. Obviously it won't be approved like this.

**Comment by jcardus** [comment]
This started in the forum.

**Comment by jcardus** [comment]
#4524

**Comment by tananaev** [comment]
I still want to see proper description. What code does, what information is provided by JMX, what are the security implication... etc.

**Comment by jcardus** [comment]
I'm just enabling a configuration which is already available on jetty configuration files. We have to do it this way because we use the embedded version.

All that it does and all the information jetty puts on JMX is available in the [link](https://www.eclipse.org/jetty/documentation/current/jmx-chapter.html) I used for the documentation.

This allows you to monitor your traccar instance a lot easier. In my case I use a java agent which puts a lot of metrics in amazon cloudwatch for me.

This is not opening any port or any connection, it just makes jetty put jmx data on the local java virtual machine its being ran. How you expose your java virtual machine to allow jmx connection is another story and should have security concerns yes. But that's not what we're doing here.

**Pull request closed without merging**
