### PR TITLE
Chrome Cross-Site Cookie

### PR DESCRIPTION
**Pull request by jcardus**
Fixing [chrome samesite cookie problem](https://www.traccar.org/forums/topic/chrome-cross-site-cookie/)

This only works on https

### CODE REVIEW

**Comment by tananaev** [comment]
Why are there so many commits? Does it fix the issue?

**Comment by jcardus** [comment]
I still had the changes from my last PR about JMX that wasn't approved. Also had sensitive information committed by mistake. So I had to "git reset" to an old commit and then there were some merging issues.

Yes, it fixes the issue.

**Comment by tananaev** [comment]
I've updated configuration a little bit. Can you please check if it still works: https://github.com/traccar/traccar/commit/03bd0f0d0945a80f5af19d06d37ff31a52d294ed.

**Comment by jcardus** [comment]
Yeap, still works.

**Pull request merged**
