### PR TITLE
Kafka notificator

### PR DESCRIPTION
**Pull request by mvniekerk**
Send events to a Kafka stream.

### CODE REVIEW

**Comment by tananaev** [comment]
Please provide some details on why we need this. Also, why you decided to use notificator option.

**Comment by mvniekerk** [comment]
When viewed as a stream of events to be processed, Kafka is suitable. There are other Apache projects that have Kafka adapters like Flink and Pulsar, which opens more stream processing options post fact.

As for the choice on using notificator - are there other options?

**Comment by tananaev** [comment]
1. Please elaborate on "which opens more stream processing options post fact". A few concrete examples would be helpful.

2. As for notificator, it is designed to send notifications per user. It doesn't really make sense in this case. I think you want something more global. Check for example event forwarding.

3. Why not use an HTTP bridge for Kafka to forward events without integrating Kafka library directly into Traccar?

**Comment by mvniekerk** [comment]
I'll look at the event forwarding.

As for the Kafka lib -
What is more favourable - setting up another server (http bridge) or having the client talk Kafka over the wire?

**Comment by tananaev** [comment]
I think if you set up an HTTP bridge, you won't need to make any changes to Traccar code.

**Pull request closed without merging**
