### PR TITLE
Feature/filter users by id

### PR DESCRIPTION
**Pull request by kgrosvenor**
Creates a way for REST API's using admin tokens on /user endpoint to retrieve one or many users by id and also hooks into existing caching system.

This PR adds a new method to UserManager for validating a set of longs and then some extra logic within UserResource to return the expected result, i am making use of some available methods here too.

Usage for example `http://localhost:8082/api/users?id=1&id=33`

### CODE REVIEW

**Comment by tananaev** [comment]
I think it makes sense to implement something more generic.

**Comment by kgrosvenor** [comment]
What kind of scope do you think that could have so i can understand, something generic to enrich id's similar to this on all object types, how should it work?

**Comment by tananaev** [comment]
Well, if we implement this functionality, we should implement it for all models. Maybe add something to base classes.

**Comment by kgrosvenor** [comment]
Ok i'll close this PR and open another one at a later date when i've spent some more time on it, i'm getting to grips with the code base at least. 

Does it makes sense to add a method on ManageableObjects interface, then its up to us if we want to override and implement it on each manager?

**Comment by kgrosvenor** [comment]
Ah yep, i see - could have just used getItems straight from the BaseObjectManager

**Pull request closed without merging**
