### PR TITLE
Implement Device Engine Hours reset

### PR DESCRIPTION
**Pull request by Abyss777**
Implemented resetting device engine hours with total distance
 
https://www.traccar.org/forums/topic/adjust-hours-and-service/

### CODE REVIEW

**Comment by tananaev** [comment]
Should we make values nullable? So that we can reset only hours or only distance.

**Comment by Abyss777** [comment]
Why not. It will be helpful for API users, also we are loading previous values from last position, user can change only one of them, another just will be replaced with same value.

**Comment by Abyss777** [comment]
Made them nullable. If it is omitted in payload it will not go to new position.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
