### PR TITLE
Support for Piligrim M-5000/M-10000 protocol

### PR DESCRIPTION
**Pull request by anton2920**
This branch adds basic support for protocol used by Piligrim M-5000/M-10000 and probably some other devices.

### CODE REVIEW

**Comment by tananaev** [comment]
This looks like work in progress. Let me know when it's ready for review.

**Comment by anton2920** [comment]
Example:

```
POST /push.do HTTP/1.0
Host: wayker.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 198
Connection: close
user-agent: Piligrim-M7 (#76)

&phoneNumber=%2B+7800XXXXXXX&message=ALARM KEY; $GPRMC,180752.000,A,XXXX.0857,N,XXXXX.8173,E,0.00,104.74,220722,,,A,V* 29,05; GSM: XXX-XX XXXX-XXXX,XXXX,XXXX,XXXX,XXXX 25;  S; Batt: 405,M
```

I've replaced private information with `X`, but overall structure should be clear. Also, instead of `ALARM KEY; `, it's possible that message has nothing or some other words, which depend on event. All of those are currently ignored.

**Comment by tananaev** [comment]
A quick question here. Is there a reason you didn't use our standard way of decoding text data? We have many examples of NMEA decoding.

**Comment by tananaev** [comment]
Refactor if you want to merge to your local version - https://github.com/traccar/traccar/commit/4de8efe1ef0810af492c161bfc1d3200958d75d8.

**Pull request merged**
