### PR TITLE
Fix RST V10.02 firmware version compatibility

### PR DESCRIPTION
**Pull request by riccefarias**
adjustes firmware regex length to allow reading most recent firmwares.

### CODE REVIEW

**Comment by tananaev** [comment]
Please attach the documentation and add a unit test.

**Comment by riccefarias** [comment]
I found the problem using raw, you are free to use it if you want, if you don't, I'm sure someone will pay me to do it.

**Comment by tananaev** [comment]
You have to provide at least the sample.

**Comment by riccefarias** [comment]
like that?

"RST;L;RST-MINI-4Gv3;V10.02;009544344;177;1;09-08-2024 11:35:19;09-08-2024 11:35:21;-9.976116;-67.835190;0;89;218;1;12;0;00;B0;00;1A;02;12.24;4.00;16;23;FE;0000;01;C0;00800061;0;167;2;4;4;0;434.0000;6;0;-66;703;16662;724;255;63;00000000;FIM;"

**Comment by tananaev** [comment]
Yes, thanks.

**Pull request merged**
