### PR TITLE
Implement header authentication for reverse proxies

### PR DESCRIPTION
**Pull request by dan-r**
I host Traccar behind a reverse proxy that handles authentication. Because of this, having Traccar automatically authenticate users based on a header provided by the proxy would be useful.

This of course puts a lot of trust in the reverse proxy, so ideally an IP range check would be added too, but I wanted to share a 'prototype' solution to get the general consensus on this feature before continuing with it.

In my environment, to test this I set web.headerAuth to Remote-Email, which my haproxy instance fills with the users email. I tested and plan to use this with LDAP - it may make sense to lock it down to only LDAP, but again I wanted to get the views of the community/maintainers.

### CODE REVIEW

**Comment by tananaev** [comment]
Seems like a very specific use case. Not sure if it makes sense unless we can generify this.

I'm also not sure I understand the LDAP role in this. If your proxy is doing the authentication, then why do you need LDAP?

**Comment by dan-r** [comment]
A more useful implementation may be using OIDC to implement proper SSO instead of this reverse proxy approach (there's some interest in #4207 by the looks of it).

With my specific implementation, the LDAP server just serves to assign the admin role and trigger the initial account creation.

**Comment by tananaev** [comment]
Proper SSO with generic implementation will definitely be useful.

**Comment by dan-r** [comment]
Okay I'll close this PR and start working on an SSO implementation.
 
@tananaev do you have any issue with an SSO implementation using OpenID Connect? 

From my point of view it seems like the current de facto standard and would allow authenticating against private directories like Keyclock, Authelia and Auth0 and also against third-parties like Google. 

My current implementation idea is a new endpoint (maybe under /api/session) to initiate the SSO login, and to provide a configuration option to either allow local login alongside SSO or to skip the login page and go straight to the SSO provider.

**Comment by tananaev** [comment]
OpenID Connect makes sense. I would recommend drawing a simple diagram or something like that before actually starting coding, so we get on the same page about the implementation details.

**Comment by dan-r** [comment]
So focusing on the OIDC code flow, I'd propose 2 new API endpoints:
- /api/session/openid/auth - Checks for an existing session and redirects to identity provider if necessary 
- /api/session/openid/callback - Callback URL for the identity provider

I'd also add the following configuration variables:
- oidc.enable - boolean state
- oidc.force - true = don't show Traccar login page, redirect straight to identity provider
- oidc.clientId - OIDC client ID
- oidc.authURL - OIDC authorization URL
- oidc.tokenURL - OIDC token URL
- oidc.userinfoURL - OIDC user info URL
- oidc.adminGroup - OIDC group to grant admin access

The proposed implementation steps would be:
- Add config keys to Config.java
- Add new API endpoints to SessionResource.java
- Create a new module in org.traccar.api.security to handle everything SSO
  - Potentially refactor some of LoginService.java if a lot of it is ending up copied to the new module
- Add a redirect for when oidc.force is true to either traccar-web logic or WebServer.java
- Update tests, Swagger spec and documentation

 Diagram

**Comment by tananaev** [comment]
Sounds reasonable to me. I think we can go ahead with the implementation.

**Comment by dan-r** [comment]
Just moved across to the issue at #5056, apologies, messed up this PR with my fork branch.

**Pull request closed without merging**
