### PR TITLE
Fix ERI for GV350M

### PR DESCRIPTION
**Pull request by AymanElarian**
Hello ,

GV350 fail as we are taking 
 index += 1; // reserved / uart device type

### CODE REVIEW

**Comment by tananaev** [comment]
This change doesn't make sense. The documentation says that the field should be there.

**Comment by AymanElarian** [comment]
please try  test case , without this pull request it will fail , with , it will pass

verifyAttributes(decoder, buffer(
                 "+RESP:GTERI,F18501,862599050498599,GV350M_HHP,00000002,,51,1,1,18.9,140,319.5,46.586093,28.985816,20240817120402,0420,0001,03DA,AC81,,0.0,,,0,220100,,0,20240817120401,7860$"));

**Comment by tananaev** [comment]
That doesn't mean that your fix is correct.

**Comment by AymanElarian** [comment]
the position fully decoded. I agree that the reserved fields and UART device type are necessary, but I'm unsure why it functions as expected. It might be due to unnecessary calls to index+ or similar methods being invoked prematurely.

**Comment by tananaev** [comment]
Well, we need to figure out the reason and have a proper fix.

**Pull request closed without merging**
