### PR TITLE
Update TrvProtocolDecoder.java

### PR DESCRIPTION
**Pull request by Nikutrax**
Correction from CP01 to AP01

### CODE REVIEW

**Comment by tananaev** [comment]
What is this?

**Comment by tananaev** [comment]
You have to provide more context if you want a send a PR. And if anything it should probably be an addition, not a change.

**Comment by Nikutrax** [comment]
position.set("bloodSugar", Double.parseDouble(values[5]));

insteat of

position.set("bloodSugar", Integer.parseInt(values[5]));

**Comment by Nikutrax** [comment]
because i think the documention was fail and should so

**Comment by Nikutrax** [comment]
> position.set("bloodSugar", Double.parseDouble(values[5]));
> 
> insteat of
> 
> position.set("bloodSugar", Integer.parseInt(values[5]));

on line 348

**Comment by tananaev** [comment]
This is not what we talked about.

**Pull request closed without merging**
