### PR TITLE
Fix the asynchronous position issue

### PR DESCRIPTION
**Pull request by ssianky**
The asyncronous upstreams are executed last and position is updated in the database afterward.

### CODE REVIEW

**Comment by tananaev** [comment]
This is incorrect solution. Position has to be set as last only when it's fully processed.

**Comment by ssianky** [comment]
Then you shouldn't write positions into database if any asynchronous precessing fails, but you do that.

**Comment by ssianky** [comment]
Anyway, I don't think there's a better solution for the issue.

**Comment by tananaev** [comment]
We shouldn't we write position if async processing failed? Are you saying losing data is better?

**Comment by ssianky** [comment]
> Position has to be set as last only when it's fully processed.

You said that. So if the asynchronous precessing fails - it's not fully processed and the last position shouldn't be set.

**Comment by tananaev** [comment]
Failed asynchronous request doesn't mean it hasn't been processed. It just means we didn't get information, so whatever data we were requesting will be empty in the position.

**Comment by ssianky** [comment]
Yeah, and in my case it will work the same - if the asynchronous processing fails, it will remain null. The difference is that it won't destroy all other processings.

**Comment by tananaev** [comment]
Failed asynchronous call is a corner case. Successful one is not. If we do geocoding after everything else it's probably not a big deal, but GSM-based location can affect other handlers and needs to be done first.

**Comment by ssianky** [comment]
So I agree that the geolocation was intended as an additional way to find the track's location  so it's not good to move it to the end. I guess I will just remove it altogether since it's useless how it's made.

But the geocode is fine to work at the end. It's not a problem not having the address.

Anyway, the fact that asynchronous precessing fucks all other processings is worse. I don't know if that can be somehow fixed in a better way.

**Comment by tananaev** [comment]
There is a better way. We need to delay processing of next position until first one is fully processed. It's not easy, but it's possible to implement.

**Comment by tananaev** [comment]
Using synchronous network calls is not a good practice.

**Pull request closed without merging**
